version: '3'

services:
  db:
    container_name: postgresql
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USER: algalog
      POSTGRES_PASSWORD: algalog
      POSTGRES_DATABASE: algalog
    ports:
      - '5432:5432'
    volumes:
      - algalog_data:/var/lib/postgresql/data

volumes:
  algalog_data:
    driver: local
